name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install TeX Live and XeLaTeX
        run: |
            sudo apt-get update
            sudo apt-get install -y texlive texlive-xetex
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
            r-version: '4.3.3'
        
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
            pandoc-version: '2.19'
            
      - name: Install dependencies
        run: |
          install.packages(c("bookdown", "markdown", "data.table", "dplyr", "bindrcpp", "ggplot2", "summarytools", "gapminder", "ggpubr", "xtable"))
        shell: Rscript {0}
        
      - name: Build book
        run: |
             Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
             Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          folder: docs
          branch: gh-pages
